### ISSUE TITLE
Generate Icons UI is partially blank

### ISSUE THREAD

**Issue by BretJohnson** [deanchalk/XAMLAssetCreator#1]
First off, this is pretty cool & thanks for sharing it.

I installed and played with it some and saw the blank-ish UI below for the Generate Icons dialog. Just a heads up on that, if you weren't aware of the issue.

![image](https://user-images.githubusercontent.com/245892/82246521-d7f77000-9912-11ea-979e-7e6c20378557.png)

**Comment by deanchalk** [comment]
That's very strange, will look into it - thanks for letting me know

**Comment by deanchalk** [comment]
I have fixed this and checked in the fix. I hadnt tested properly in the dark theme. Ive published an app update to the Microsoft store, so you should get that update within a few hours
