### ISSUE TITLE
Add feature to create ttf font from selected icons

### ISSUE THREAD

**Issue by mdmozibur** [deanchalk/XAMLAssetCreator#2]

**Comment by deanchalk** [comment]
Thanks for the idea, Its a good idea, but I think beyond the intended scope of this application. I will keep it in mind, but I will probably create a different app for that - thanks

**Comment by mdmozibur** [comment]
If you do create an application of that sort in future, please mention it here.

**Comment by deanchalk** [comment]
I certainly will - thanks for the idea :)
